import type { Metadata } from 'next'
import Layout from '@/components/Layout'
import { Montserrat_Alternates } from 'next/font/google'

import './globals.css'

const montserratAlternates = Montserrat_Alternates({
  weight: '300',
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserratAlternates.className}>
        <Layout>
          <div className='flex-1'>
            {children}
          </div>
        </Layout>
      </body>
    </html>
  )
}
