import type { Metadata } from 'next'
import Layout from '@/components/Layout'
import { Montserrat_Alternates } from 'next/font/google'
// import { Lexend } from 'next/font/google';

import '../styles/globals.scss'
import '../styles/globalicon.scss'

const montserratAlternates = Montserrat_Alternates({
  weight: '300',
  subsets: ['latin'],
  display: 'swap'
})

// class for connecting icon, but it doesnt need when we already has one
// const lexend = Lexend({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserratAlternates.className}>
        <Layout>
          <div className='flex-1 p-12'>
            {children}
          </div>
        </Layout>
      </body>
    </html>
  )
}
